# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95a16f83618abb8413a4023a2baebc32390b2f90c911d72be8a9cd6dfe50d7a06ef78baaa5507a3df90c38d4a33de144aaad40887739b5c67fadc5787443f25d

test:
  secret_key_base: c106e872d38cf03d473ce3c1e71ee14e1dbee1bdebe0ce6702a4f5e1d7c59908b9d7898cc6e53a4df18f62579d1ea32880e4c59727373e7c7abb0e6b6c48da19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
